import type { ZenPreset } from "@/types/settings";

export interface ZenThemeTokens {
  id: ZenPreset;
  name: string;
  description: string;
  mode: "light" | "dark";
  background: string;
  foreground: string;
  card: string;
  cardForeground: string;
  muted: string;
  mutedForeground: string;
  accent: string;
  accentForeground: string;
  border: string;
  ring: string;
  planned: string;
  unplanned: string;
}

export const ZEN_PRESETS: Record<ZenPreset, ZenThemeTokens> = {
  "calm-teal": {
    id: "calm-teal",
    name: "Calm Teal",
    description: "Deep zinc with serene teal accents",
    mode: "dark",
    background: "#09090b",
    foreground: "#f4f4f5",
    card: "rgba(24, 24, 27, 0.8)",
    cardForeground: "#f4f4f5",
    muted: "#27272a",
    mutedForeground: "#a1a1aa",
    accent: "#0d9488",
    accentForeground: "#f0fdfa",
    border: "rgba(255, 255, 255, 0.06)",
    ring: "#14b8a6",
    planned: "#10b981",
    unplanned: "#f59e0b",
  },
  "warm-arc": {
    id: "warm-arc",
    name: "Warm Arc",
    description: "Soft stone warmth with amber highlights",
    mode: "light",
    background: "#fafaf9",
    foreground: "#292524",
    card: "rgba(255, 255, 255, 0.85)",
    cardForeground: "#292524",
    muted: "#f5f5f4",
    mutedForeground: "#78716c",
    accent: "#d97706",
    accentForeground: "#fffbeb",
    border: "rgba(28, 25, 23, 0.08)",
    ring: "#f59e0b",
    planned: "#059669",
    unplanned: "#ea580c",
  },
  "forest-zen": {
    id: "forest-zen",
    name: "Forest Zen",
    description: "Deep forest tones with sage green",
    mode: "dark",
    background: "#0c0f0d",
    foreground: "#e7e5e4",
    card: "rgba(6, 44, 34, 0.35)",
    cardForeground: "#e7e5e4",
    muted: "#1c1917",
    mutedForeground: "#a8a29e",
    accent: "#4d7c0f",
    accentForeground: "#ecfccb",
    border: "rgba(255, 255, 255, 0.05)",
    ring: "#65a30d",
    planned: "#22c55e",
    unplanned: "#ca8a04",
  },
  "monochrome-focus": {
    id: "monochrome-focus",
    name: "Monochrome Focus",
    description: "Distraction-free neutral palette",
    mode: "dark",
    background: "#0a0a0a",
    foreground: "#f5f5f5",
    card: "rgba(23, 23, 23, 0.9)",
    cardForeground: "#f5f5f5",
    muted: "#262626",
    mutedForeground: "#a3a3a3",
    accent: "#737373",
    accentForeground: "#fafafa",
    border: "rgba(255, 255, 255, 0.08)",
    ring: "#a3a3a3",
    planned: "#a3a3a3",
    unplanned: "#d4d4d4",
  },
  "soft-dawn": {
    id: "soft-dawn",
    name: "Soft Dawn",
    description: "Gentle sunrise warmth with rose accents",
    mode: "light",
    background: "#fff7ed",
    foreground: "#44403c",
    card: "rgba(255, 255, 255, 0.95)",
    cardForeground: "#44403c",
    muted: "#ffedd5",
    mutedForeground: "#78716c",
    accent: "#fb7185",
    accentForeground: "#fff1f2",
    border: "rgba(68, 64, 60, 0.1)",
    ring: "#fda4af",
    planned: "#16a34a",
    unplanned: "#f97316",
  },
  "deep-night": {
    id: "deep-night",
    name: "Deep Night",
    description: "Midnight zinc with indigo glow",
    mode: "dark",
    background: "#09090b",
    foreground: "#d4d4d8",
    card: "rgba(24, 24, 27, 0.85)",
    cardForeground: "#d4d4d8",
    muted: "#27272a",
    mutedForeground: "#71717a",
    accent: "#6366f1",
    accentForeground: "#eef2ff",
    border: "rgba(255, 255, 255, 0.06)",
    ring: "#818cf8",
    planned: "#34d399",
    unplanned: "#fbbf24",
  },
  "ocean-mist": {
    id: "ocean-mist",
    name: "Ocean Mist",
    description: "Coastal blues with seafoam calm",
    mode: "dark",
    background: "#0b1220",
    foreground: "#e2e8f0",
    card: "rgba(15, 23, 42, 0.75)",
    cardForeground: "#e2e8f0",
    muted: "#1e293b",
    mutedForeground: "#94a3b8",
    accent: "#38bdf8",
    accentForeground: "#f0f9ff",
    border: "rgba(148, 163, 184, 0.12)",
    ring: "#7dd3fc",
    planned: "#2dd4bf",
    unplanned: "#fb923c",
  },
  "lavender-haze": {
    id: "lavender-haze",
    name: "Lavender Haze",
    description: "Soft violet light with gentle focus",
    mode: "light",
    background: "#faf5ff",
    foreground: "#3b0764",
    card: "rgba(255, 255, 255, 0.92)",
    cardForeground: "#3b0764",
    muted: "#f3e8ff",
    mutedForeground: "#7e22ce",
    accent: "#a855f7",
    accentForeground: "#faf5ff",
    border: "rgba(88, 28, 135, 0.1)",
    ring: "#c084fc",
    planned: "#059669",
    unplanned: "#ea580c",
  },
  "slate-minimal": {
    id: "slate-minimal",
    name: "Slate Minimal",
    description: "Clean slate workspace for clarity",
    mode: "light",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "rgba(255, 255, 255, 0.95)",
    cardForeground: "#0f172a",
    muted: "#e2e8f0",
    mutedForeground: "#64748b",
    accent: "#475569",
    accentForeground: "#f8fafc",
    border: "rgba(15, 23, 42, 0.08)",
    ring: "#94a3b8",
    planned: "#0d9488",
    unplanned: "#d97706",
  },
  "sunset-glow": {
    id: "sunset-glow",
    name: "Sunset Glow",
    description: "Warm dusk tones with coral energy",
    mode: "dark",
    background: "#1a0f0f",
    foreground: "#fde68a",
    card: "rgba(41, 20, 16, 0.8)",
    cardForeground: "#fef3c7",
    muted: "#292524",
    mutedForeground: "#d6d3d1",
    accent: "#f97316",
    accentForeground: "#fff7ed",
    border: "rgba(251, 146, 60, 0.15)",
    ring: "#fdba74",
    planned: "#4ade80",
    unplanned: "#facc15",
  },
  "paper-zen": {
    id: "paper-zen",
    name: "Paper Zen",
    description: "Washi-inspired cream — easy on the eyes for long sessions",
    mode: "light",
    background: "#f7f4ef",
    foreground: "#2c2825",
    card: "rgba(255, 255, 255, 0.9)",
    cardForeground: "#2c2825",
    muted: "#ede8e0",
    mutedForeground: "#6b6560",
    accent: "#8b7355",
    accentForeground: "#faf8f5",
    border: "rgba(44, 40, 37, 0.09)",
    ring: "#a08b6e",
    planned: "#2f7d5a",
    unplanned: "#c45c26",
  },
  "sage-morning": {
    id: "sage-morning",
    name: "Sage Morning",
    description: "Soft botanical greens — calm focus for wellness-minded workflows",
    mode: "light",
    background: "#f4f7f4",
    foreground: "#1a2e1a",
    card: "rgba(255, 255, 255, 0.92)",
    cardForeground: "#1a2e1a",
    muted: "#e4ece4",
    mutedForeground: "#5a6f5a",
    accent: "#4a7c59",
    accentForeground: "#f0fdf4",
    border: "rgba(26, 46, 26, 0.08)",
    ring: "#6b9b7a",
    planned: "#2d6a4f",
    unplanned: "#d97706",
  },
  "sky-clarity": {
    id: "sky-clarity",
    name: "Sky Clarity",
    description: "Clear blue-white — trusted productivity palette used worldwide",
    mode: "light",
    background: "#f5f9fc",
    foreground: "#0f2942",
    card: "rgba(255, 255, 255, 0.95)",
    cardForeground: "#0f2942",
    muted: "#e8f0f7",
    mutedForeground: "#5a7a94",
    accent: "#2563eb",
    accentForeground: "#eff6ff",
    border: "rgba(15, 41, 66, 0.08)",
    ring: "#60a5fa",
    planned: "#0d9488",
    unplanned: "#ea580c",
  },
  "sandstone": {
    id: "sandstone",
    name: "Sandstone",
    description: "Warm neutral sand — low-glare comfort for bright environments",
    mode: "light",
    background: "#f5f0e8",
    foreground: "#3d3428",
    card: "rgba(255, 255, 255, 0.88)",
    cardForeground: "#3d3428",
    muted: "#ebe4d8",
    mutedForeground: "#7a7062",
    accent: "#a67c38",
    accentForeground: "#fffbeb",
    border: "rgba(61, 52, 40, 0.1)",
    ring: "#c9a55c",
    planned: "#4a7c59",
    unplanned: "#c2410c",
  },
  "ink-studio": {
    id: "ink-studio",
    name: "Ink Studio",
    description: "True OLED black — maximum contrast and battery efficiency",
    mode: "dark",
    background: "#000000",
    foreground: "#f5f5f5",
    card: "rgba(18, 18, 18, 0.95)",
    cardForeground: "#f5f5f5",
    muted: "#1a1a1a",
    mutedForeground: "#a3a3a3",
    accent: "#d4d4d4",
    accentForeground: "#0a0a0a",
    border: "rgba(255, 255, 255, 0.1)",
    ring: "#e5e5e5",
    planned: "#4ade80",
    unplanned: "#fbbf24",
  },
  "sakura-night": {
    id: "sakura-night",
    name: "Sakura Night",
    description: "Soft mauve dusk — gentle contrast popular in East Asian UI design",
    mode: "dark",
    background: "#1a1218",
    foreground: "#f5e6ef",
    card: "rgba(40, 24, 36, 0.82)",
    cardForeground: "#f5e6ef",
    muted: "#2a1f28",
    mutedForeground: "#c4a8b8",
    accent: "#e879a8",
    accentForeground: "#fdf2f8",
    border: "rgba(232, 121, 168, 0.12)",
    ring: "#f0abce",
    planned: "#6ee7b7",
    unplanned: "#fcd34d",
  },
  "nordic-noir": {
    id: "nordic-noir",
    name: "Nordic Noir",
    description: "Cool slate blues — Scandinavian clarity for structured thinking",
    mode: "dark",
    background: "#0f1419",
    foreground: "#e8edf2",
    card: "rgba(22, 30, 40, 0.88)",
    cardForeground: "#e8edf2",
    muted: "#1a222d",
    mutedForeground: "#8b9cad",
    accent: "#5b8def",
    accentForeground: "#eff6ff",
    border: "rgba(139, 156, 173, 0.12)",
    ring: "#7ba3f0",
    planned: "#34d399",
    unplanned: "#f59e0b",
  },
  "earth-clay": {
    id: "earth-clay",
    name: "Earth Clay",
    description: "Terracotta warmth — grounded tones inspired by Mediterranean spaces",
    mode: "dark",
    background: "#1c1410",
    foreground: "#f0e6dc",
    card: "rgba(44, 32, 24, 0.88)",
    cardForeground: "#f0e6dc",
    muted: "#2a2018",
    mutedForeground: "#b8a090",
    accent: "#c87941",
    accentForeground: "#fff7ed",
    border: "rgba(200, 121, 65, 0.14)",
    ring: "#daa06a",
    planned: "#65a30d",
    unplanned: "#eab308",
  },
  "coral-bloom": {
    id: "coral-bloom",
    name: "Coral Bloom",
    description: "Soft peach blush — uplifting warmth for creative, expressive work",
    mode: "light",
    background: "#fff5f2",
    foreground: "#3d2020",
    card: "rgba(255, 255, 255, 0.92)",
    cardForeground: "#3d2020",
    muted: "#ffe8e2",
    mutedForeground: "#8a5c52",
    accent: "#e85d4c",
    accentForeground: "#fff5f2",
    border: "rgba(61, 32, 32, 0.09)",
    ring: "#f4a89a",
    planned: "#2f7d5a",
    unplanned: "#d97706",
  },
  "mint-breeze": {
    id: "mint-breeze",
    name: "Mint Breeze",
    description: "Cool seafoam light — refreshing clarity for calm, focused afternoons",
    mode: "light",
    background: "#f0faf8",
    foreground: "#0f2e2a",
    card: "rgba(255, 255, 255, 0.93)",
    cardForeground: "#0f2e2a",
    muted: "#ddf5f0",
    mutedForeground: "#4a7a72",
    accent: "#14b8a6",
    accentForeground: "#f0fdfa",
    border: "rgba(15, 46, 42, 0.08)",
    ring: "#5eead4",
    planned: "#059669",
    unplanned: "#ea580c",
  },
};

/** Curated display order — neutrals → nature → cool → warm */
export const DARK_ZEN_PRESET_IDS = [
  "calm-teal",
  "monochrome-focus",
  "ink-studio",
  "deep-night",
  "forest-zen",
  "ocean-mist",
  "nordic-noir",
  "sunset-glow",
  "earth-clay",
  "sakura-night",
] as const satisfies readonly ZenPreset[];

/** Curated display order — minimal → nature → warm → expressive */
export const LIGHT_ZEN_PRESET_IDS = [
  "slate-minimal",
  "sky-clarity",
  "paper-zen",
  "sandstone",
  "mint-breeze",
  "warm-arc",
  "soft-dawn",
  "sage-morning",
  "lavender-haze",
  "coral-bloom",
] as const satisfies readonly ZenPreset[];

export function applyZenPreset(preset: ZenPreset): void {
  const tokens = ZEN_PRESETS[preset];
  const root = document.documentElement;

  root.style.setProperty("--background", tokens.background);
  root.style.setProperty("--foreground", tokens.foreground);
  root.style.setProperty("--card", tokens.card);
  root.style.setProperty("--card-foreground", tokens.cardForeground);
  root.style.setProperty("--muted", tokens.muted);
  root.style.setProperty("--muted-foreground", tokens.mutedForeground);
  root.style.setProperty("--accent", tokens.accent);
  root.style.setProperty("--accent-foreground", tokens.accentForeground);
  root.style.setProperty("--border", tokens.border);
  root.style.setProperty("--ring", tokens.ring);
  root.style.setProperty("--planned", tokens.planned);
  root.style.setProperty("--unplanned", tokens.unplanned);
  root.dataset.zenPreset = preset;
  root.dataset.themeMode = tokens.mode;
}