import type { CommandItem } from "./command-types";

export const NAVIGATION_ITEMS: CommandItem[] = [
  {
    id: "page-board",
    type: "page",
    label: "Board",
    description: "Daily task board",
    href: "/board",
    keywords: ["kanban", "tasks", "today"],
  },
  {
    id: "page-reports",
    type: "page",
    label: "Reports",
    description: "Weekly stats and reflections",
    href: "/reports",
    keywords: ["stats", "analytics", "weekly"],
  },
  {
    id: "page-chat",
    type: "page",
    label: "Companion",
    description: "AI chat with local context",
    href: "/chat",
    keywords: ["ai", "assistant", "chat"],
  },
  {
    id: "page-tags",
    type: "page",
    label: "Tags & Categories",
    description: "Manage tags and categories",
    href: "/tags",
    keywords: ["labels", "organize"],
  },
  {
    id: "page-settings",
    type: "page",
    label: "Settings",
    description: "App preferences",
    href: "/settings",
    keywords: ["preferences", "config"],
  },
  {
    id: "page-settings-account",
    type: "page",
    label: "Account",
    description: "Username and workspace name",
    href: "/settings/account",
    keywords: ["profile", "username", "workspace"],
  },
  {
    id: "page-settings-appearance",
    type: "page",
    label: "Appearance",
    description: "Zen presets, theme, and calendar",
    href: "/settings/appearance",
    keywords: ["theme", "zen", "preset", "week start"],
  },
  {
    id: "page-settings-ai",
    type: "page",
    label: "AI Configuration",
    description: "Provider, model, and API key",
    href: "/settings/ai",
    keywords: ["openai", "api", "model", "llm"],
  },
  {
    id: "page-settings-app",
    type: "page",
    label: "App",
    description: "Install, offline use, and updates",
    href: "/settings/app",
    keywords: ["pwa", "install", "offline"],
  },
  {
    id: "page-settings-data",
    type: "page",
    label: "Data & Privacy",
    description: "Export, import, and reset",
    href: "/settings/data",
    keywords: ["export", "import", "backup", "privacy"],
  },
  {
    id: "page-settings-about",
    type: "page",
    label: "About",
    description: "Version, credits, and copyright",
    href: "/settings/about",
    keywords: ["version", "credits"],
  },
];